discussion/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from discussion.views import (
    BasicForumViewSet, CategoryViewSet, CommentFileViewSet, CommentLikeViewSet, CommentViewSet,
    ContentFileViewSet, ForumCreateView, ForumDeleteView, ForumFileViewSet,
    ForumListView, ForumSearchViewSet, ForumUpdateView, ForumView, ForumViewSet,
    TagViewSet, TopicFileViewSet, TopicLikeViewSet, TopicNotificationViewSet,
    TopicPageViewSet, TopicReadViewSet, TopicTypeaheadViewSet, TopicViewSet, ForumPageViewSet,
    CategoryPageViewSet
)

from rest_framework import routers


app_name = 'discussion'

router = routers.SimpleRouter(trailing_slash=False)
router.register(r'category', CategoryViewSet)
router.register(r'category_page', CategoryPageViewSet)
router.register(r'forum', ForumViewSet) 
router.register(r'basic_forum', BasicForumViewSet)
router.register(r'forum_page', ForumPageViewSet)
router.register(r'topic', TopicViewSet)
router.register(r'topic_page', TopicPageViewSet)
router.register(r'comment', CommentViewSet)
router.register(r'tag', TagViewSet)
router.register(r'topic-notification', TopicNotificationViewSet)
router.register(r'comment_like', CommentLikeViewSet)
router.register(r'comment-file', CommentFileViewSet)
router.register(r'topic_like', TopicLikeViewSet)
router.register(r'forum-file', ForumFileViewSet)
router.register(r'topic-file', TopicFileViewSet)
router.register(r'content-file', ContentFileViewSet)
router.register(r'topic-read', TopicReadViewSet)
router.register(r'search', ForumSearchViewSet)
router.register(r'typeahead', TopicTypeaheadViewSet)

urlpatterns = [

    url(r'^api/', include(router.urls)),
    url(r'^$', ForumView.as_view(), name='forum'),
    url(r'^admin/forum-create$', ForumCreateView.as_view(), name='forum-create'),
    url(r'^admin$', ForumListView.as_view(), name='forum-list'),
    url(r'^admin/forum-update/(?P<pk>[-a-zA-Z0-9_]+)$', ForumUpdateView.as_view(), name='forum-update'),
    url(r'^admin/forum-delete/(?P<pk>[-a-zA-Z0-9_]+)$', ForumDeleteView.as_view(), name='forum-delete'),
    url(r'^topic/(?:#(?P<topic_id>[-a-zA-Z0-9_]+))?$', TemplateView.as_view(template_name="forum-topic.html")),
    url(r'^topic/new/', TemplateView.as_view(template_name="forum-new-topic.html")),
    url(r'^forum/embed/$', TemplateView.as_view(template_name="forum-embed.html")),
    url(r'^home/$', RedirectView.as_view(url='/discussion/', permanent=False), name='forum-home'),

    # Templates for Angular components
    url(r'^forum-summary.template.html', TemplateView.as_view(template_name="components/forum-summary.template.html")),
    url(r'^topic-create.template.html', TemplateView.as_view(template_name="components/topic-create.template.html")),
    url(r'^topic-detail.template.html', TemplateView.as_view(template_name="components/topic-detail.template.html")),
]

discussion/templates/forum-list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block js %} {{ block.super }}
  <script type="text/javascript" src="{% static 'js/my-courses/app.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/controllers.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/services.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/filters.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/truncate.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/factories/timtec-models.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/directives/fixedBar.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/directives/file.js' %}"></script>
  <script>window.user_id = {{ user.pk }};</script>
{% endblock %}

{% block wrapper_classes %}
  wrapper-course-lesson
{% endblock %}

{% block body_attrs %}
  ng-app="my-courses"
{% endblock %}


{% block content %}
  <div class="page container-fluid forum-admin forum-list">
    <header class="page-header">
      <div class="pull-right"><a class="btn btn-primary add" href="/discussion/admin/forum-create" translate>New forum</a></div>
      <h2 translate>Forums' list</h2>
    </header>
    {% for forum in object_list %}
      <div class="row">
        <div class="col-xs-12 col-sm-7">
          <span><a href="/#!/forum/{{ forum.id }}">{{ forum.title }}</a></span>
        </div>
        <div class="col-xs-12 col-sm-5 actions">
          <a class="btn btn-primary edit" href="{% url 'discussion:forum-update' forum.id %}" translate>Edit</a>
          <a class="btn btn-danger delete" href="{% url 'discussion:forum-delete' forum.id %}" translate>Delete</a>
        </div>
      </div>
    {% empty %}
      <p>Ainda não há fóruns cadastrados.</p>
    {% endfor %}
  </div>
{% endblock %}

discussion/templates/forum_create_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block js %} {{ block.super }}
  <script type="text/javascript" src="{% static 'js/admin/edit-forum/app.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/admin/edit-forum/controllers.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/truncate.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/factories/timtec-models.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/directives/fixedBar.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/directives/file.js' %}"></script>
  <script>window.user_id = {{ user.pk }};</script>
{% endblock %}

{% block wrapper_classes %}
  wrapper-course-lesson
{% endblock %}

{% block body_attrs %}
  ng-app="edit-forum"
{% endblock %}


{% block content %}
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
       $("select[multiple]").mousedown(function(e){
            e.preventDefault();

            var select = this;
            var scroll = select.scrollTop;

            e.target.selected = !e.target.selected;

            setTimeout(function(){select.scrollTop = scroll;}, 0);

            $(select).focus();
        }).mousemove(function(e){e.preventDefault()});
    });
  </script>
  <div class="page container-fluid" ng-controller="ForumEditCtrl">
    <header class="page-header">
      <h2 translate>New forum</h2>
    </header>
    <form action="" method="post" class="forum-admin">
      {% csrf_token %}
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label translate>Title</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.title }}
        </div>
        {% for err in form.title.errors %}
        <small>{{ err }}</small>
        {% endfor %}
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label translate>Text</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.text }}
        </div>
      </div>
      <!--
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label>Categoria</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.category }}
        </div>
        {% for err in form.category.errors %}
        <small>{{ err }}</small>
        {% endfor %}
      </div>
      -->
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label translate>User groups</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.groups }}
        </div>
        {% for err in form.groups.errors %}
        <small>{{ err }}</small>
        {% endfor %}
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label translate>Make it public</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.is_public }}
        </div>
      </div>
      <input type="submit" class="btn btn-primary pull-right" {%verbatim%}value="{{'Criar fórum' | translate}}"{%endverbatim%}/>
    </form>
  </div>
{% endblock %}

discussion/templates/forum_delete_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block js %} {{ block.super }}
  <script type="text/javascript" src="{% static 'js/my-courses/app.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/controllers.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/services.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/filters.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/factories/timtec-models.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/directives/fixedBar.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/directives/file.js' %}"></script>
  <script>window.user_id = {{ user.pk }};</script>
{% endblock %}

{% block wrapper_classes %}
  wrapper-course-lesson
{% endblock %}

{% block body_attrs %}
  ng-app="my-courses"
{% endblock %}


{% block content %}
  <div class="page container-fluid">
    <header class="page-header">
      <h2 translate>Delete forum</h2>
    </header>
    <form action="" method="post"  class="forum-admin">{% csrf_token %}
      <p><span translate>Are you sure you want to remove</span> "{{ object }}"?</p>
      <input class="btn btn-primary pull-right" type="submit" {%verbatim%}value="{{'Confirm'|translate}}"{%endverbatim%} />
    </form>
  </div>
{% endblock %}

discussion/templates/forum_update_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block js %} {{ block.super }}
  <script type="text/javascript" src="{% static 'js/my-courses/app.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/controllers.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/services.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/my-courses/filters.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/factories/timtec-models.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/directives/fixedBar.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/directives/file.js' %}"></script>
  <script>window.user_id = {{ user.pk }};</script>
{% endblock %}

{% block wrapper_classes %}
  wrapper-course-lesson
{% endblock %}

{% block body_attrs %}
  ng-app="my-courses"
{% endblock %}


{% block content %}
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
       $("select[multiple]").mousedown(function(e){
            e.preventDefault();

            var select = this;
            var scroll = select.scrollTop;

            e.target.selected = !e.target.selected;

            setTimeout(function(){select.scrollTop = scroll;}, 0);

            $(select).focus();
        }).mousemove(function(e){e.preventDefault()});
    });
  </script>
  <div class="page container-fluid">
    <header class="page-header">
      <h2 translate>Update forum</h2>
    </header>
    <form action="" method="post" class="forum-admin">
      {% csrf_token %}
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label translate>Title</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.title }}
        </div>
        {% for err in form.title.errors %}
        <small>{{ err }}</small>
        {% endfor %}
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label translate>Text</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.text }}
        </div>
      </div>
      <!--
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label>Categoria</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.category }}
        </div>
        {% for err in form.category.errors %}
        <small>{{ err }}</small>
        {% endfor %}
      </div>
      -->
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label translate>User groups</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.groups }}
        </div>
        {% for err in form.groups.errors %}
        <small>{{ err }}</small>
        {% endfor %}
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-3">
          <label translate>Make it public</label>
        </div>
        <div class="col-xs-12 col-md-9">
          {{ form.is_public }}
        </div>
      </div>
      <input type="submit" class="btn btn-primary pull-right" {%verbatim%}value="{{'Update forum' | translate}}"{%endverbatim%}/>
    </form>
  </div>
{% endblock %}